name: Run Tests

on:
  push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "lts/*"
          cache: false

      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1
        with:
          bot-id: "BT01KPGC0DQQM4GSQJXHGAJ7C87G"

      - name: Install dependencies
        run: npm ci

      - name: Run CI tests
        run: npm run test:ci

      - name: Can build
        run: npm run build
